Repository openimsdk/wiseengage, pull requests merged in 2023-10, with the labels that each got.

#204 docs: update and fix docs Link
  docs/website/README.md
Labels: size/XS

#200 feat: Add knowledge base support.
  bot/apis/__init__.py
  bot/apis/chat.py
  bot/apis/docs.py
  bot/config.example.yaml
  bot/config.yaml
  bot/constants/request.py
  bot/constants/response.py
  bot/db/__init__.py
  bot/db/milvus.py
  bot/main.py
  bot/requirements.txt
  bot/router/__init__.py
  bot/router/router.py
  bot/test/README.md
  bot/test/openim.txt
  bot/test/test_langchain.py
  bot/utils/config.py
Labels: size/L

#208 fix: Update readme cmd.
  README_zh-CN.md
Labels: size/S
