Repository openimsdk/wiseengage, pull requests merged in 2023-06, with the labels that each got.

#5 feat: init server project
  .gitignore
  api/README.md
  configs/OWNERS
  configs/README.md
  configs/config.yaml
  examples/OWNERS
  go.mod
  init/OWNERS
  init/README.md
  internal/OWNERS
  internal/README.md
  pkg/OWNERS
  pkg/version/version.go
  server/README.md
  server/cmd/README.md
  server/config-example.yaml
  server/config.yaml
  server/docs/docs.go
  server/docs/swagger.json
  server/docs/swagger.yaml
  server/examples/README.md
  server/go.mod
  server/go.sum
  server/internal/api/auth/auth.go
  server/internal/client/mail.go
  server/internal/client/minio.go
  server/internal/config/config.go
  server/internal/config/viper.go
  server/internal/db/mysql.go
  server/internal/db/redis.go
  server/internal/e/code.go
  server/internal/e/msg.go
  server/internal/middleware/cros.go
  server/internal/middleware/jwt.go
  server/internal/router/router.go
  server/internal/utils/utils.go
  server/main.go
  server/models/.gitkeep
  server/pkg/OWNERS
  server/pkg/README.md
  server/pkg/log/fileline_hook.go
  server/pkg/log/logrus.go
  server/pkg/server/server.go
  server/pkg/utils/jwt.go
  server/pkg/utils/strings.go
  server/test/OWNERS
  server/test/README.md
  server/tools/README.md
  test/OWNERS
  third_party/README.md
Labels: size/XXL

#8 Fix: fix review problems.
  server/config-example.yaml
  server/config.yaml
  server/go.mod
  server/go.sum
  server/internal/config/config.go
  server/internal/config/viper.go
  server/internal/utils/banner.go
  server/main.go
  server/pkg/log/logrus.go
  web/.gitignore
  web/OWNERS
  web/README.md
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/.gitkeep
  web/scripts/setup.sh
  web/src/App.vue
  web/src/api/openim.js
  web/src/assets/.gitkeep
  web/src/components/.gitkeep
  web/src/constant/constant.js
  web/src/main.js
  web/src/router/index.js
  web/src/utils/loading.js
  web/src/utils/request.js
  web/src/views/.gitkeep
  web/vite.config.js
Labels: size/L

#11 feat: enhance automated review for codeowners
  docs/CODEOWNERS
Labels: size/M

#14 feat: init plugin project.
  kf_plugins/README.md
  kf_plugins/chat/__init__.py
  kf_plugins/config.yaml
  kf_plugins/config/__init__.py
  kf_plugins/config_example.yaml
  kf_plugins/data/.gitkeep
  kf_plugins/logs/.gitkeep
  kf_plugins/main.py
  kf_plugins/model/__init__.py
  kf_plugins/requirements.txt
  kf_plugins/utils/__init__.py
  kf_plugins/utils/log.py
Labels: size/M

#28 fix: Fix CONTRIBUTING.
  CONTRIBUTING.md
  server/internal/api/auth.go
  server/internal/api/mail.go
  server/internal/common/response/response.go
  server/internal/models/base.go
  server/internal/models/user.go
  server/internal/param/mail.go
  server/internal/service/init.go
  server/internal/service/mail.go
  server/internal/utils/code.go
  web/src/api/openim.js
  web/src/constant/constant.js
Labels: size/L

#33 fix: make fix
  .github/workflows/codeql-analysis.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/kubekf.yml
  .golangci.yml
  Makefile
  README.md
  docs/CODEOWNERS
  docs/roadmap/OpenKF-2023.md
  server/go.mod
  server/go.sum
  server/internal/api/mail.go
  server/internal/common/response/response.go
  server/internal/conn/db/mysql.go
  server/pkg/log/fileline_hook.go
  server/pkg/log/logrus.go
  server/pkg/server/server.go
Labels: size/L

#35 docs: Update README
  README.md
  README_zh-CN.md
  assets/images/architecture.png
  assets/images/mvc.png
Labels: size/L

#30 feat: add prettier and eslint (#18)
  web/.eslintrc.js
  web/.prettierignore
  web/.prettierrc.js
  web/index.html
  web/package-lock.json
  web/package.json
  web/src/App.vue
  web/src/main.js
  web/src/router/index.js
  web/src/utils/loading.js
  web/src/utils/request.js
  web/vite.config.js
Labels: size/L

#39 fix: Fix golang ci piplines and docs.
  .github/workflows/golangci-lint.yml
  .github/workflows/kubekf.yml
  .golangci.yml
  Makefile
  README.md
  README_zh-CN.md
  server/cmd/genhooks/pkg/gen.go
  server/go.mod
  server/go.sum
  server/internal/api/mail.go
  server/internal/common/code.go
  server/internal/common/msg.go
  server/internal/common/response/response.go
  server/internal/config/config.go
  server/internal/config/viper.go
  server/internal/conn/client/mail.go
  server/internal/conn/client/minio.go
  server/internal/conn/db/mysql.go
  server/internal/conn/db/redis.go
  server/internal/middleware/cros.go
  server/internal/middleware/hooks/global_hook.go
  server/internal/middleware/hooks/init.go
  server/internal/middleware/hooks/mail_hook.go
  server/internal/middleware/hooks/url_trie/hook.go
  server/internal/middleware/hooks/url_trie/trie.go
  server/internal/middleware/jwt.go
  server/internal/models/base.go
  server/internal/models/user.go
  server/internal/param/mail.go
  server/internal/router/router.go
  server/internal/service/init.go
  server/internal/service/mail.go
  server/pkg/log/fileline_hook.go
  server/pkg/log/logrus.go
  server/pkg/server/server.go
Labels: size/L

#41 fix: Fix doc links.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/link-pr.yml
  CONTRIBUTING.md
  DEVELOPGUIDE.md
  README_zh-CN.md
Labels: size/S
