Repository openimsdk/wiseengage, pull requests merged in 2023-09, with the labels that each got.

#173 feat: fix githook and set openkf build images ci
  .github/release-drafter.yml
  .github/workflows/build-docker-image.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  build/goreleaser.yaml
  deploy/docker/Dockerfile.web
  scripts/githooks/commit-msg.sh
  scripts/githooks/pre-commit.sh
  scripts/githooks/pre-push.sh
  scripts/init-githooks.sh
  scripts/template/LICENSE
  scripts/template/LICENSE_TEMPLATES
  scripts/template/boilerplate.txt
  scripts/template/footer.md.tmpl
  scripts/template/head.md.tmpl
  scripts/template/project_README.md
  server/go.mod
Labels: size/XL

#175 Feature: Support unit test in go.1
  server/pkg/utils/utils_test.go
  server/test/README.md
  server/test/integration_test.go
  web/package-lock.json
  web/package.json
Labels: size/L

#177 fix: Update start event.
  bot/llm/fastchat_api_runner.py
Labels: size/XS

#178 Feature: Support unit test in go.2
  .github/workflows/kubekf.yml
  server/pkg/utils/utils_test.go
  server/test/log_test.go
Labels: size/L

#181 Feature: Support unit test in go.3
  server/test/config_test.go
Labels: size/L

#187 fix: Update config and append influx docker config
  bot/requirements.txt
  deploy/docker-compose/docker-compose.yaml
  server/config.example.yaml
  server/config.yaml
  server/go.mod
  server/go.sum
  server/internal/conn/client/minio.go
  web/.env.development
  web/vite.config.ts
Labels: size/L

#192 feat: Update user statistics graphs.
  web/package-lock.json
  web/package.json
  web/src/api/index/statistics.ts
  web/src/api/request/userModel.ts
  web/src/api/response/userModel.ts
  web/src/constants/index.ts
  web/src/views/dashboard/components/StatisticCard.vue
Labels: size/L

#190 feature:update redis client
  server/internal/conn/db/redis.go
  server/internal/dal/cache/redis.go
  server/test/redis_mock.go
Labels: size/XL

#195 fix: Update chart options.
  web/src/constants/date.ts
  web/src/views/dashboard/components/StatisticCard.vue
Labels: size/M

#189 feat: Add user statistics api with influxdb.
  server/config.docker.yaml
  server/config.example.yaml
  server/config.yaml
  server/go.mod
  server/go.sum
  server/internal/api/callback.go
  server/internal/api/user_statistics.go
  server/internal/config/config.go
  server/internal/conn/db/influxdb.go
  server/internal/dal/dao/dao.go
  server/internal/dal/dao/user_statistic_dao.go
  server/internal/params/request/user.go
  server/internal/params/response/user.go
  server/internal/router/router.go
  server/internal/service/im_callback.go
  server/internal/service/user_statistic.go
  server/internal/utils/struct_helper.go
  server/main.go
  web/src/views/layouts/components/LayoutSideNav.vue
Labels: size/XL

#197 feat: Add milvus db server.
  bot/test/README.md
  bot/test/test_milvus.py
  deploy/docker-compose/docker-compose.yaml
Labels: size/L
