Repository openimsdk/wiseengage, pull requests merged in 2023-07, with the labels that each got.

#29 feat: add a component to support rate limt control
  server/internal/middleware/frequency_control.go
Labels: good first issue, size/M, API

#43 Update README.md
  README.md
Labels: size/XS

#47 Add priority to hooks.
  server/cmd/genhooks/main.go
  server/cmd/genhooks/pkg/gen.go
  server/internal/middleware/hooks/global_hook.go
  server/internal/middleware/hooks/mail_hook.go
  server/internal/middleware/hooks/url_trie/trie.go
  server/internal/middleware/hooks/url_trie/trie_test.go
Labels: size/M

#50 docs: update code owners file
  docs/CODEOWNERS
Labels: size/XS

#49 feat: Support auto-signature.
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  scripts/githooks/commit-msg
  server/cmd/genhooks/main.go
  server/cmd/genhooks/pkg/gen.go
  server/cmd/genhooks/pkg/template.go
  server/go.mod
Labels: size/M

#59 Docs: add issue-specification-document
  docs/ISSUE_SPECIFICATION.md
Labels: size/M

#66 Docs: modify issue-specification.md
  docs/contribution/issue specification.md
Labels: size/M

#68 docs: design openkf docs
  .github/workflows/kubekf.yml
  Dockerfile
  Makefile
  docs/contribution/issue specification.md
  docs/contribution/issue_specification.md
  docs/images/openkf-log.png
  docs/test/e2e.md
  docs/test/integration.md
  docs/website/.gitignore
  docs/website/Makefile
  server/internal/router/router.go
Labels: size/L

#83 feat: Register with OpenIMServer in HTTP Method.
  Makefile
  server/config-example.yaml
  server/config.yaml
  server/go.mod
  server/go.sum
  server/internal/config/config.go
  server/internal/service/user.go
  server/pkg/openim/client/client.go
  server/pkg/openim/param/request/auth.go
  server/pkg/openim/param/request/user.go
  server/pkg/openim/param/response/response.go
  server/pkg/openim/sdk/auth/auth.go
  server/pkg/openim/sdk/auth/auth_test.go
  server/pkg/openim/sdk/user/user.go
  server/pkg/openim/sdk/user/user_test.go
Labels: size/XL

#86 feat: Add register and login page with TDesign.
  assets/logo/favicon.ico
  web/.eslintignore
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/favicon.ico
  web/src/assets/openkf-logo.svg
  web/src/main.ts
  web/src/router/index.ts
  web/src/style/index.less
  web/src/style/reset.less
  web/src/style/theme.css
  web/src/views/login/components/Header.vue
  web/src/views/login/components/Login.vue
  web/src/views/login/components/Register.vue
  web/src/views/login/index.less
  web/src/views/login/index.vue
  web/vite.config.ts
Labels: size/XXL

#91 fix: docs link
  .github/sync.yml
  .github/workflows/kubekf.yml
  .github/workflows/stale.yml
  .github/workflows/sync.yml
  .gitignore
  CHANGELOG/.chglog/CHANGELOG.tpl.md
  CHANGELOG/.chglog/config.yml
  CHANGELOG/CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG.md
  CONTRIBUTING.md
  DEVELOPGUIDE.md
  Makefile
  README.md
  README_zh-CN.md
  assets/logo-gif/LICENSE
  assets/logo/LICENSE
  docs/CODEOWNERS
  docs/OWNERS
  docs/website/.gitignore
  docs/website/Makefile
  docs/website/README.md
  docs/website/theme.toml
  package-lock.json
Labels: size/XL

#96 feat: add the changelog
  .github/workflows/kubekf.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  README_zh-CN.md
Labels: size/L

#99 Update README_zh-CN.md
  README_zh-CN.md
Labels: size/S

#100 Update CODEOWNERS
  docs/CODEOWNERS
Labels: size/XS

#104 feat: Use wasm to login to OpenIM.
  server/config-example.yaml
  server/config.yaml
  server/internal/config/config.go
  server/internal/params/response/user.go
  server/internal/service/mail.go
  server/internal/service/user.go
  server/internal/utils/jwt.go
  web/.env
  web/.env.development
  web/README.md
  web/scripts/setup.sh
  web/src/api/index/login.ts
  web/src/api/openim/index.ts
  web/src/api/request/openimModel.ts
  web/src/api/response/userModel.ts
  web/src/constants/index.ts
  web/src/types/env.d.ts
  web/src/views/login/components/LoginForm.vue
Labels: size/L

#105 feat: Add light mode and dark mode.(#89)
  web/.eslintrc.js
  web/package.json
  web/src/router/index.ts
  web/src/views/login/components/LoginHeader.vue
  web/src/views/login/index.less
  web/src/views/login/index.vue
Labels: size/M

#107 fix: Update format.
  Makefile
  server/internal/dal/gen/sys_community.gen.go
  server/internal/models/base/model.go
  server/internal/models/base/user_base.go
  server/internal/models/system_roles/sys_bot.go
  server/internal/models/system_roles/sys_customer.go
  server/internal/models/system_roles/sys_user.go
  server/internal/params/request/bot.go
  server/internal/params/request/community.go
  server/internal/params/request/user.go
  server/pkg/openim/param/request/auth.go
  server/pkg/openim/param/request/user.go
  web/src/views/login/components/LoginHeader.vue
  web/src/views/login/index.vue
Labels: size/M

#109 fix: makefile in windows goos
  Makefile
Labels: size/S

#110 fix: reduce `for range` expression overhead
  server/cmd/dbmigration/main.go
Labels: size/S

#113 docs: Update login page.
  README.md
  README_zh-CN.md
  assets/images/login_page.png
Labels: size/XS

#122 feat: Add data validation(#90)
  web/src/utils/common/cache.ts
  web/src/views/login/components/LoginForm.vue
  web/src/views/login/components/RegisterForm.vue
  web/src/views/login/index.vue
Labels: size/L

#125 feat: Support multi urls matching.
  server/cmd/dbmigration/main.go
  server/cmd/genhooks/pkg/template.go
  server/internal/middleware/hooks/gen_cors_hook.go
  server/internal/middleware/hooks/gen_jwt_hook.go
  server/internal/middleware/hooks/gen_rate_hook.go
  server/internal/middleware/hooks/global_hook.go
  server/internal/middleware/hooks/mail_hook.go
  server/internal/middleware/hooks/url_trie/hook.go
  server/internal/middleware/hooks/url_trie/trie.go
  server/internal/middleware/hooks/url_trie/trie_test.go
Labels: size/L

#131 Create cla.yml
  .github/workflows/cla.yml
Labels: size/M

#133 Update cla.yml
  .github/workflows/cla.yml
Labels: size/XS

#132 feat: Add roadmap.
  ROADMAP.md
Labels: size/S

#135 feat: Add server dockerfile and docker-compose.
  deploy/README.md
  deploy/docker-compose/docker-compose-dev.yaml
  deploy/docker/Dockerfile.server
  server/config.docker.yaml
  server/docker_init_server.sh
Labels: size/L

#137 test: net and endless replace
  .github/workflows/auto-assign-issue.yml
  .github/workflows/auto-gh-pr.yml
  .github/workflows/cla.yml
  .github/workflows/e2e-test.yml
  .github/workflows/kubekf.yml
  Makefile
  README.md
  README_zh-CN.md
  assets/logo-gif/openkf-logo.gif
  build/OWNERS
  deploy/OWNERS
  server/pkg/server/server.go
  server/test/OWNERS
Labels: size/L

#134 feat: Add web dockerfile.
  .gitignore
  deploy/README.md
  deploy/docker/Dockerfile.web
  server/config.example.yaml
  web/.dockerignore
Labels: size/M
