Repository openimsdk/wiseengage, pull requests merged in 2023-08, with the labels that each got.

#151 docs: Update config page.
  README.md
  README_zh-CN.md
  assets/images/config_page.png
Labels: size/S

#144 feat: Add config pages.
  server/internal/api/admin.go
  server/internal/params/request/bot.go
  server/internal/params/request/user.go
  server/internal/params/response/user.go
  server/internal/router/router.go
  server/internal/service/bot.go
  server/internal/service/user.go
  server/main.go
  web/src/api/index/admin.ts
  web/src/api/index/bot.ts
  web/src/api/index/community.ts
  web/src/api/index/user.ts
  web/src/api/request/botModel.ts
  web/src/api/request/commonModel.ts
  web/src/api/request/communityModel.ts
  web/src/api/request/userModel.ts
  web/src/api/response/botModel.ts
  web/src/api/response/menuModel.ts
  web/src/api/response/userModel.ts
  web/src/assets/openkf-logo-landscape.png
  web/src/router/index.ts
  web/src/store/menu/index.ts
  web/src/store/setting/index.ts
  web/src/store/user/index.ts
  web/src/style/common.less
  web/src/style/index.less
  web/src/style/reset-tdesign.less
  web/src/style/reset.less
  web/src/style/theme.css
  web/src/types/interface.d.ts
  web/src/utils/common/string.ts
  web/src/views/config/components/BotDialog.vue
  web/src/views/config/components/BotTable.vue
  web/src/views/config/components/ConfigForm.vue
  web/src/views/config/components/ConfigList.vue
  web/src/views/config/components/GroupDialog.vue
  web/src/views/config/components/GroupTable.vue
  web/src/views/config/components/KnowledgeBaseDialog.vue
  web/src/views/config/components/KnowledgeBaseTable.vue
  web/src/views/config/index.less
  web/src/views/config/index.vue
  web/src/views/dashboard/index.vue
  web/src/views/health/index.vue
  web/src/views/layouts/components/LayoutContent.vue
  web/src/views/layouts/components/LayoutSideNav.vue
  web/src/views/layouts/index.vue
  web/src/views/login/components/LoginForm.vue
  web/src/views/platform/index.vue
  web/src/views/session/index.vue
  web/src/views/setting/index.vue
Labels: size/XXL

#155 feat: Add dashboard pages v1.
  web/package-lock.json
  web/package.json
  web/src/constants/color.ts
  web/src/constants/date.ts
  web/src/store/user/index.ts
  web/src/utils/common/color.ts
  web/src/utils/common/string.ts
  web/src/utils/common/time.ts
  web/src/views/dashboard/components/MemberCard.vue
  web/src/views/dashboard/components/StatisticCard.vue
  web/src/views/dashboard/index.less
  web/src/views/dashboard/index.vue
  web/src/views/layouts/components/LayoutContent.vue
Labels: size/XL

#153 feat：Add talk pages（#116）
  web/.env.development
  web/src/components/Message.vue
  web/src/components/PopMessage.vue
  web/src/views/chat/components/ChatInputBox.vue
  web/src/views/chat/components/ChatMessageBox.vue
  web/src/views/chat/index.vue
  web/src/views/login/components/LoginForm.vue
Labels: size/L

#152 feat: Add platform pages.
  .gitignore
  server/config.docker.yaml
  server/config.example.yaml
  server/config.yaml
  server/internal/api/platform.go
  server/internal/config/config.go
  server/internal/middleware/hooks/gen_jwt_hook.go
  server/internal/params/response/platform.go
  server/internal/router/router.go
  server/internal/service/slack.go
  web/src/api/index/platform.ts
  web/src/api/response/platformModel.ts
  web/src/constants/index.ts
  web/src/style/reset-tdesign.less
  web/src/types/interface.d.ts
  web/src/views/platform/components/PlatformCard.vue
  web/src/views/platform/components/PlatformDialog.vue
  web/src/views/platform/index.less
  web/src/views/platform/index.vue
Labels: size/XL

#164 feat: Add user dispatch with redis zset.
  server/internal/api/callback.go
  server/internal/api/platform.go
  server/internal/api/user.go
  server/internal/dal/cache/redis.go
  server/internal/dal/cache/redis_test.go
  server/internal/dal/dao/slacker_marshal_helper.go
  server/internal/dal/dao/user_dispatch_dao.go
  server/internal/middleware/hooks/gen_jwt_hook.go
  server/internal/msg/slack_cmd/slack.go
  server/internal/params/request/msg.go
  server/internal/router/router.go
  server/internal/service/slack.go
  server/internal/service/user.go
  server/internal/service/user_dispatch.go
  server/internal/service/user_dispatch_test.go
  server/pkg/openim/sdk/auth/auth_test.go
  server/pkg/openim/sdk/msg/msg.go
  web/src/api/index/login.ts
  web/src/api/index/platform.ts
  web/src/api/response/platformModel.ts
  web/src/constants/index.ts
  web/src/views/layouts/components/LayoutSideNav.vue
  web/src/views/session/components/SessionWindow.vue
Labels: size/XXL

#168 feat: LLM server start with fastchat multiprocess.
  .github/workflows/kubekf.yml
  bot/.gitignore
  bot/README.md
  bot/__init__.py
  bot/chains/__init__.py
  bot/config.example.yaml
  bot/config.yaml
  bot/constants/__init__.py
  bot/constants/constants.py
  bot/llm/__init__.py
  bot/llm/fastchat_api_runner.py
  bot/main.py
  bot/models/.gitkeep
  bot/requirements.txt
  bot/utils/__init__.py
  bot/utils/banner.py
  bot/utils/config.py
  bot/utils/log.py
  kf_plugins/utils/log.py
Labels: size/XL

#170 docs: Update system preview and architecture.
  README.md
  README_zh-CN.md
  assets/images/architecture.png
  assets/images/dashboard_page.png
  assets/images/platform_page.png
  assets/images/session_page.png
Labels: size/M
